POST http://localhost:5000/api/auth/signup
Content-Type: application/json

{
    "fullName": "James Joe",
    "username": "jamee",
    "password": "1234569",
    "confirmPassword": "1234569",
    "gender": "male"
}




